version: '3.8'

services:
  web:
    build: .
    command: uvicorn hook:app --reload --host 0.0.0.0 --port 8081
    volumes:
      - .:/app
    ports:
      - "8001:443"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: